MOV SI,1000H     
MOV DI,1010H
MOV BP,1020H         
MOV CL,03H
MOV CH,03H 
MOV DH,CH
  REPEAT3:            
MOV BL,DH                    
 REPEAT2:            
 MOV DL,00H                    
 MOV CH,DH 
  REPEAT1:           
MOV AL,[SI]
 MUL [DI] 
 ADD DL,AL
INC SI
ADD DI,03
DEC CH
JNZ REPEAT1
MOV [BP],DL
INC BP
SUB SI,03H
SUB DI,09H
INC DI
DEC BL
JNZ REPEAT2
ADD SI,03H
MOV DI,1010H
DEC CL 
JNZ REPEAT3
HLT